Source/GoSport.Client/Controllers/AdvancedController.cs
using GoSport.Client.Infrastructure;
using GoSport.Client.Infrastructure.Mapping;
using GoSport.Client.ViewModels.Advanced;
using GoSport.Client.ViewModels.SportCenters;
using GoSport.Services;
using GoSport.Services.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoSport.Client.Controllers
{
    public class AdvancedController : BaseController
    {
        ISportCenterService sportCenterService;

        public AdvancedController(
            ISportCategoryService sportCategories,
            IAddressService addressService,
            ISportCategoryService categoryService,
            ISportCenterService sportCenterService)
            : base(sportCategories, addressService, categoryService)
        {
            this.sportCenterService = sportCenterService;
        }

        [HttpGet]
        public ActionResult BySortPreferance()
        {
            return RedirectToAction("ByPreferance");
        }

        [HttpGet]
        public ActionResult ByPreferance()
        {
            var model = GetByQueryStringParameter().ToList();

            GetImageUrls(model);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ByPreferance(SearchViewModel model)
        {
            string city = string.Empty;
            string neighbour = string.Empty;
            if (model.City != 0) city = addressService.All().FirstOrDefault(x => x.Id == model.City).City;
            if (model.Neighborhood != 0) neighbour = addressService.All().FirstOrDefault(x => x.Id == model.Neighborhood).Neighborhood;
            var cityOrNeighbourPassed = (city != string.Empty || neighbour != string.Empty);

            var fromCitiesAndNeihbours = sportCenterService.All()
                .Where(x => city != string.Empty ? x.Address.City == city : x.Address.City == null)
                .Where(x => neighbour != string.Empty ? x.Address.Neighborhood == neighbour : x.Address.Neighborhood == null)
                .To<SportCenterViewModel>()
                .ToList();

            // cities and neighbours
            if (string.IsNullOrEmpty(neighbour))
            {
                fromCitiesAndNeihbours = sportCenterService.All()
                .Where(x => city != string.Empty ? x.Address.City == city : x.Address.City == null)
                .To<SportCenterViewModel>()
                .ToList();
            }

            // categories
            var categoriesNames = new List<string>();

            if (model.SportCategories != null)
            {
                categoriesNames = Array
                    .ConvertAll(model.SportCategories.Split(','), p => p.Trim()).Where(x => !string.IsNullOrEmpty(x)).ToList();
            }

            var fromCategories = new List<SportCenterViewModel>();

            foreach (var category in categoriesNames)
            {
                var current = categoryService.All()
                    .FirstOrDefault(x => x.Name == category);

                if (current != null)
                {
                    fromCategories.AddRange(current.SportCenters
                    .AsQueryable()
                    .To<SportCenterViewModel>().ToList());
                }

            }

            var resultSportCenters = new List<SportCenterViewModel>();

            if (fromCitiesAndNeihbours.Count > 0 && fromCategories.Count > 0)
            {
                resultSportCenters = fromCitiesAndNeihbours
                    .Where(x => fromCategories.Any(y => y.Name == x.Name))
                    .ToList();
            }
            else if (fromCategories.Count > 0 && !cityOrNeighbourPassed)
            {
                resultSportCenters = fromCategories;
            }
            else if(cityOrNeighbourPassed)
            {
                resultSportCenters = fromCitiesAndNeihbours
                    .Where(x => city != string.Empty ? x.Address.City == city : x.Address.City != null)
                    .Where(x => neighbour != string.Empty ? x.Address.Neighborhood == neighbour : x.Address.Neighborhood != null)
                    .ToList();
            }

            this.GetImageUrls(resultSportCenters);

            return View(resultSportCenters);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BySortPreferance(string sortParam)
        {
            var model = new List<SportCenterViewModel>();

            if (sortParam != null || sortParam != string.Empty)
            {
                if (sortParam == "Rating")
                {
                    model = sportCenterService.All()
                            .OrderByDescending(x => x.Rating.Total)
                            .To<SportCenterViewModel>()
                            .ToList();
                }
                if (sortParam == "Date")
                {
                    model = sportCenterService.All()
                            .OrderByDescending(x => x.CreatedOn)
                            .To<SportCenterViewModel>()
                            .ToList();
                }
                if (sortParam == "Name")
                {
                    model = sportCenterService.All()
                            .OrderBy(x => x.Name)
                            .To<SportCenterViewModel>()
                            .ToList();
                }
                if (sortParam == "Most comments")
                {
                    model = sportCenterService.All()
                            .OrderByDescending(x => x.Comments.Count())
                            .To<SportCenterViewModel>()
                            .ToList();
                }
            }
            else
            {
                model = sportCenterService.All()
                .OrderByDescending(x => x.CreatedOn)
                .To<SportCenterViewModel>()
                .ToList();
            }

            GetImageUrls(model);

            return this.View("ByPreferance", model);
        }

        private IEnumerable<SportCenterViewModel> GetByQueryStringParameter()
        {
            if (Request.QueryString["City"] != null)
            {
                var param = (string)Request.QueryString["City"];

                return sportCenterService.All()
                      .OrderByDescending(x => x.CreatedOn)
                      .Where(x => x.Address.City == param)
                      .To<SportCenterViewModel>();
            }

            if (Request.QueryString["Neighbour"] != null)
            {
                var param = (string)Request.QueryString["Neighbour"];

                return sportCenterService.All()
                      .OrderByDescending(x => x.CreatedOn)
                      .Where(x => x.Address.Neighborhood == param)
                      .To<SportCenterViewModel>();
            }

            if (Request.QueryString["category"] != null)
            {
                var param = (string)Request.QueryString["category"];

                return categoryService.All()
                      .OrderByDescending(x => x.CreatedOn)
                      .FirstOrDefault(x => x.Name == param)
                      .SportCenters
                      .AsQueryable()
                      .To<SportCenterViewModel>();
            }

            return sportCenterService.All()
                        .OrderByDescending(x => x.CreatedOn)
                        .To<SportCenterViewModel>();
        }

        private void GetImageUrls(IEnumerable<SportCenterViewModel> collection)
        {
            foreach (var sportCenter in collection)
            {
                sportCenter.Images = ImageHelper.SanitizeImageUrls(sportCenterService.GetImagesForSportCenter(sportCenter.Name).ToArray());
            }
        }
    }
}

Source/GoSport.Client/Controllers/SportCenterController.cs
using GoSport.Services.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoSport.Client.ViewModels.SportCenters;
using GoSport.Client.Infrastructure.Mapping;
using GoSport.Data.Models;
using System.IO;
using GoSport.Client.Infrastructure;
using Microsoft.AspNet.Identity;
using GoSport.Client.ViewModels.Comments;

namespace GoSport.Client.Controllers
{
    public class SportCenterController : BaseController
    {
        ISportCenterService sportCenterService;

        public SportCenterController(
            ISportCategoryService sportCategories,
            IAddressService addressService,
            ISportCategoryService categoryService,
            ISportCenterService sportCenterService)
            : base(sportCategories, addressService, categoryService)
        {
            this.sportCenterService = sportCenterService;
        }

        public ActionResult SportCenters()
        {
            var all = sportCenterService.All().To<SportCenterViewModel>().ToList();

            Response.Write("All sport centers are: " + all.Count());
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {


            var model = Mapper.Map<SportCenterViewModel>(sportCenterService.GetById(id));

            model.Images = ImageHelper.SanitizeImageUrls(sportCenterService.GetImagesForSportCenter(model.Name).ToArray());

            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AddSportCenterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var sportCenter = Mapper.Map<SportCenter>(model);

                sportCenter = sportCenterService.Create(sportCenter);

                // address
                int addressId;
                if (int.TryParse(model.Neighborhood, out addressId))
                {
                    addressService.AddAddressForSportCenter(sportCenter.Name, addressId);
                }

                // categories
                if (model.SportCategories != null)
                {
                    var categoriesNames = Array
                    .ConvertAll(model.SportCategories.Split(','), p => p.Trim())
                    .Where(x => !string.IsNullOrEmpty(x)).ToList();

                    categoryService.AddCategoriesForSportCenter(categoriesNames, sportCenter.Name);
                }

                this.AddImages(model);

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        private void AddImages(AddSportCenterViewModel model)
        {
            var imagesUrls = new List<string>();

            if (model.UplodadedImage1 != null)
            {
                var image = ImageHelper.SaveImage(this.sportCenterPath, model.UplodadedImage1, model.Name, 1);
                imagesUrls.Add(image);
            }
            if (model.UplodadedImage2 != null)
            {
                var image = ImageHelper.SaveImage(this.sportCenterPath, model.UplodadedImage2, model.Name, 2);
                imagesUrls.Add(image);
            }
            if (model.UplodadedImage3 != null)
            {
                var image = ImageHelper.SaveImage(this.sportCenterPath, model.UplodadedImage3, model.Name, 3);
                imagesUrls.Add(image);
            }
            if (model.UplodadedImage4 != null)
            {
                var image = ImageHelper.SaveImage(this.sportCenterPath, model.UplodadedImage4, model.Name, 4);
                imagesUrls.Add(image);
            }
            if (model.UplodadedImage5 != null)
            {
                var image = ImageHelper.SaveImage(this.sportCenterPath, model.UplodadedImage5, model.Name, 5);
                imagesUrls.Add(image);
            }
            if (model.UplodadedImage6 != null)
            {
                var image = ImageHelper.SaveImage(this.sportCenterPath, model.UplodadedImage6, model.Name, 6);
                imagesUrls.Add(image);
            }
            if (model.UplodadedImage7 != null)
            {
                var image = ImageHelper.SaveImage(this.sportCenterPath, model.UplodadedImage7, model.Name, 7);
                imagesUrls.Add(image);
            }
            if (model.UplodadedImage8 != null)
            {
                var image = ImageHelper.SaveImage(this.sportCenterPath, model.UplodadedImage8, model.Name, 8);
                imagesUrls.Add(image);
            }
            if (model.UplodadedImage9 != null)
            {
                var image = ImageHelper.SaveImage(this.sportCenterPath, model.UplodadedImage9, model.Name, 9);
                imagesUrls.Add(image);
            }

            sportCenterService.AddImagesToSportCenter(model.Name, imagesUrls);
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddComment(int sportCenterId, string content)
        {
            if (ModelState.IsValid && sportCenterId != 0 && content != null && content != string.Empty)
            {
                sportCenterService.AddCommentToSportCenter(sportCenterId, User.Identity.GetUserId(), content);
                var sportCenter = sportCenterService.GetById(sportCenterId);
                //var model = new List<CommentViewModel>();
                var allComments = sportCenter.Comments.ToList();

                //return RedirectToAction("Details", new { @id = sportCenterId });
                return PartialView("_AllCommentsPartial", allComments);
            }

            throw new HttpException(400, "Invalid comment");
        }
    }
}

Source/GoSport.Client/Views/Shared/_AddCommentPartial.cshtml
@model int
<div class="row">
    <a href="javascript:void(0)"
       class="btn btn-primary col-md-2 col-md-offset-5"
       id="add-comment" value="Add Comment">Add Comment</a>
</div>
<br />
<div class="row">
    <div class="add-comment col-md-6 col-md-offset-3 hidden">
        <br />
        <div class="form-group">
            @using (Ajax.BeginForm("AddComment",
                new AjaxOptions
                {
                    HttpMethod = "POST",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId="comments"
                }))
            {
                @Html.AntiForgeryToken()
                <input type="hidden" name="sportCenterId" value="@Model"></input>
                <div class="row col-md-offset-2">
                    <br />
                    <div class="col-md-2">Content</div>
                    <textarea class="col-md-7" rows="4" cols="300" placeholder="Your text here..." name="content"></textarea>
                </div>
                    <br />
                    <div class="row">
                        <input type="submit" class="btn btn-primary center-block" />
                    </div>
            }
        </div>
        <br />
    </div>
    <br />
</div>

Source/GoSport.Client/Views/Shared/_AddressPartial.cshtml
@using GoSport.Client.ViewModels
@model AddressViewModel
<div class="form-group">
    @Html.LabelFor(m => m.City, new { @class = "col-md-2 control-label" })
    <div class="col-md-6">
        @Html.DropDownListFor(m => m.City, new SelectList(ViewBag.Cities, "Id", "City"), "None", new { @class = "form-control", id = "city-drop-down" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Neighborhood, new { @class = "col-md-2 control-label" })
    <div class="col-md-6">
        @Html.DropDownListFor(m => m.Neighborhood, new SelectList(new string[] { }), "None", new { @class = "form-control", id = "neighbour-drop-down" })
    </div>
</div>

Source/GoSport.Client/Views/Shared/_AllCommentsPartial.cshtml
@using GoSport.Data.Models
@model IEnumerable<Comment>
<h1 class="row text-center">Comments</h1>
@if (Model.OrderByDescending(x => x.CreatedOn).ToList().Count() == 0)
{
        <<div class="row text-center">No comments added yet...</div>
}
else
{
    foreach (var comment in @Model.OrderBy(x => x.CreatedOn).ToList())
    {
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 comment">
                <div class="row">
                    <div class="col-md-3">@comment.Author.Name:  </div>
                    <div class="col-md-9">"@comment.Content"</div>
                </div>
                <div class="row">
                    <div class="col-md-3">Date created:  </div>
                    <i class="col-md-4">@comment.CreatedOn</i>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    }
}

Source/GoSport.Client/Views/Shared/_BigAvatarPartial.cshtml
@using GoSport.Client.ViewModels.Users
@model UserProfileViewModel
<a href='@String.Format("/Users/Users/Profile/{0}",Model.Id)'>
        <img src="@String.Format("/Content/Avatars/{0}.jpg",Model.UserName)"
             onError="this.onerror = null; this.src='https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRQYvnZBfeVGEm4cbMDXLlr-xOat9DQungOjV8sUGPcHgE1u3BE';"
             alt="avatar" height=70 width=70 class="img-rounded" />
</a>

Source/GoSport.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/kendo-css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/kendo")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Go Sport", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" },null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home" ,new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Search", "ByPreferance", "Advanced", new { area = "" }, null)</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Add Sport Center", "Add", "SportCenter", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Find Friends", "All", "Users", new { area = "Users" }, null)</li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="">@Html.ActionLink("Admin", "Index", "SportCenters", new { area = "Administration" }, null)</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
</body>
</html>

Source/GoSport.Client/Views/Shared/_RatingPartial.cshtml
@using GoSport.Client.ViewModels
@model RatingViewModel
    <div class="starRate col-md-6" data-rating-type="@Model.RatingType" data-sport-center-id="@Model.SportCenterId">
        <button value="1" style="cursor:pointer"><span class="glyphicon glyphicon-star"></span></button>
        <button value="2" style="cursor:pointer"><span class="glyphicon glyphicon-star"></span></button>
        <button value="3" style="cursor:pointer"><span class="glyphicon glyphicon-star"></span></button>
        <button value="4" style="cursor:pointer"><span class="glyphicon glyphicon-star"></span></button>
        <button value="5" style="cursor:pointer"><span class="glyphicon glyphicon-star"></span></button>
    </div>

Source/GoSport.Client/Views/Shared/_SportCategoriesPartial.cshtml
<div class="col-md-10">
    @(Html.Kendo().AutoComplete()
          .Name("SportCategories")
          .Filter("startswith")
          .Placeholder("Type your sports...")
          .BindTo(ViewBag.Categories)
          .Separator(",")
    )
</div>

Source/GoSport.Client/Views/Shared/_SportCenterDetailsPartial.cshtml
@using GoSport.Client.ViewModels.SportCenters
@using GoSport.Client.ViewModels
@model SportCenterViewModel

<hr />
<div class="row">
    <div class="col-md-1">
        <a href='@String.Format("/SportCenter/Details/{0}",Model.Id)'>
            @if (Model.Images.Count > 0)
            {<img src="@Model.Images.First()" alt="avatar" height=70 width=70 class="img-rounded" />}
        </a>
    </div>
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-2">Name: </div>
            <a href="\SportCenter\Details\@Model.Id" class="badge">@Model.Name</a>
        </div>
        <div class="row">
            <div class="col-md-2">City: </div>
            <a href="\Advanced\ByPreferance?City=@Model.Address.City" class="badge">@Model.Address.City</a>
        </div>
        <div class="row">
            <div class="col-md-2">Neighbour: </div>
            <a href="\Advanced\ByPreferance?Neighbour=@Model.Address.Neighborhood" class="badge">@Model.Address.Neighborhood</a>
        </div>
        <div class="row">
            <div class="col-md-2">Practiced sports: </div>
            @foreach (var item in Model.Categories)
            {
                <a href="\Advanced\ByPreferance?category=@item.Name" class="badge">@item.Name</a>
            }
        </div>
        <div class="row">
            <div class="col-md-2">Rating: </div>
            @if (Model.Rating != null)
            { <div class="col-md-2">@(Model.Rating.Total != 0 ? String.Format("{0:0.00}", Model.Rating.Total) : "Not rated yet...") </div>}
        </div>
    </div>
</div>

Source/GoSport.Client/Views/Shared/_SportCenterInfoPartial.cshtml
@using GoSport.Client.ViewModels.SportCenters
@model SportCenterViewModel
<div class="sport-center-info">
    <h1 class="col text-center"><a href="/SportCenter/Details/@Model.Id">@Model.Name</a></h1>
    <ul class="bxslider">
        @foreach (var img in Model.Images)
            {
            <li><img src="@img" height=300 width=300 class="img-rounded" /></li>
        }
    </ul>
    <div class="row col-md-offset-3">
        <div class="col-md-2">Exact Address: </div>
        <div class="col-md-4">@Model.ExactAddress</div>
    </div>
    <div class="row col-md-offset-3">
        <div class="col-md-2">City: </div>
        <a href="\Advanced\ByPreferance?City=@Model.Address.City" class="badge">@Model.Address.City</a>
    </div>
    <div class="row col-md-offset-3">
        <div class="col-md-2">Neighbour: </div>
        <a href="\Advanced\ByPreferance?Neighbour=@Model.Address.Neighborhood" class="badge">@Model.Address.Neighborhood</a>
    </div>
    <div class="row col-md-offset-3">
        <div class="col-md-2">Description: </div>
        <div class="col-md-8">@Model.Description   </div>
    </div>
    <div class="row col-md-offset-3">
        <div class="col-md-2">Practiced sports: </div>
        @foreach (var item in Model.Categories)
            {
            <a href="\Advanced\ByPreferance?category=@item.Name" class="badge">@item.Name</a>
        }
    </div>
</div>